theme: jekyll-theme-minimal
title: ğŸ’»ğŸš§ğŸ¥ğŸ“¸
description: CV's CV
analytics:
  tracking_id: G-N8B957VS8E
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      layout: "dark"
    values:
      theme: "dark"