theme: jekyll-theme-minimal
title: ğŸ’»ğŸš§ğŸ¥ğŸ“¸
description: CV's CV
google_analytics: G-C9YKR7YG6H
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      layout: "dark"
    values:
      theme: "dark"